name: axisflow
description: "A minimilistic transaction tracking app built with Flutter. It allows users to easily track their expenses and income, providing a simple and intuitive interface for managing their finances."
version: 1.0.0+1

environment:
  sdk: ^3.11.4


dependencies:
  csv: ^8.0.0
  path_provider: ^2.1.5
  share_plus: ^13.1.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fl_chart: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icon.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"